version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "RecallAssistant-backend"
s3_bucket = "recall-assistant-deploy"
s3_prefix = "RecallAssistant-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
