AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  RecallAssistant-Backend

  SAM Template for RecallAssistant Backend

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x
    Handler: app.lambdaHandler

Resources:
  # API Gateway
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: RecallAssistantAPI
      StageName: dev
      Auth:
        Authorizers:
          BasicAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt LambdaAuthorizerFunction.Arn
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 3600
        DefaultAuthorizer: BasicAuthorizer

  # CORS
  CORSLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cors/
      Events:
        CORSNotionApi:
          Type: Api
          Properties:
            Auth:
              Authorizer: NONE
            RestApiId: !Ref APIGateway
            Path: /notion
            Method: options


  # Lambda API Role
  LambdaNotionApiRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: RecallAssistantLambdaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - 'arn:aws:logs:*:*:*'
                Effect: Allow
              - Action:
                  - 'dynamodb:PutItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                  - 'dynamodb:UpdateItem'
                Resource: '*'
                Effect: Allow
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  # Lambda Authorizer
  LambdaAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: authorizer/
      Environment:
        Variables:
          username: "{{resolve:ssm:recallassistant-username}}"
          password: "{{resolve:ssm:recallassistant-password}}"

  # Get Notion API Lambda
  UpdateNotionApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt
        - LambdaNotionApiRole
        - Arn
      CodeUri: update-notion/
      Events:
        AddNotionApi:
          Type: Api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /notion
            Method: patch

  # Get Notion API Lambda
  GetNotionApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt
       - LambdaNotionApiRole
       - Arn
      CodeUri: get-notion/
      Events:
        AddNotionApi:
          Type: Api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /notion
            Method: get

  # Add Notion API Lambda
  AddNotionApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: add-notion/
      Role: !GetAtt
        - LambdaNotionApiRole
        - Arn
      Events:
        AddNotionApi:
          Type: Api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /notion
            Method: post

Outputs:
  AddNotionApi:
    Description: "API Gateway endpoint URL for dev stage for GET Notion function"
    Value:
      Fn::Sub: https://${APIGateway}.execute-api.${AWS::Region}.amazonaws.com/dev/notion/
